name: Deploy Application

on:
  push:
    branches:
      - master

# Configure this workflow
env:
  # Build/Deploy specific
  IMAGE: aniftyco/full.snack.dev
  DEPLOYMENT_NAME: fullsnackdev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            GIT_REV=${{ steps.short-sha.outputs.sha }}
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ steps.short-sha.outputs.sha }},${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to cluster
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
          kubectl set image deployment ${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.IMAGE }}:${{ steps.short-sha.outputs.sha }} --record
